
package Dibujar;

import java.awt.Graphics;
import java.awt.Color;

public class frmDoraimon extends javax.swing.JFrame {

    
    public frmDoraimon() {
        initComponents();
    }
    
     public void paint(Graphics g)
     {
    Color blue = new Color(0,100,255);
    g.setColor(blue);
    g.fillOval(150, 100, 205, 205);//para dibujar un circulo pero pintado
     
    g.setColor(Color.white);
    g.fillOval(162, 135, 180, 160);
     
    g.setColor(Color.BLACK);
    g.drawOval(193, 120, 60, 70);
    g.setColor(Color.WHITE);
    g.fillOval(193, 120, 60, 70);//ojo derecho
    
    g.setColor(Color.BLACK);
    g.drawOval(255, 120, 60, 70);
    g.setColor(Color.WHITE);
    g.fillOval(255, 120, 60, 70);//ojo izquierdo
    
    g.setColor(Color.RED);
    g.fillOval(238, 190, 30, 30);
    g.setColor(Color.BLACK);
    g.drawOval(238, 190, 30, 30);//nariz
     
    g.setColor(Color.BLACK);
    g.fillOval(223, 145, 30, 30);
    g.setColor(Color.WHITE);
    g.fillOval(240, 155, 10, 10);//PUPILAS DERECHA
    
    
    g.setColor(Color.BLACK);
    g.fillOval(256, 145, 30, 30);
    g.setColor(Color.WHITE);
    g.fillOval(258, 155, 10, 10);//PUPILA IZQUIERDA
     
    
    g.setColor(Color.WHITE);
    g.fillOval(253, 192, 10, 10);//PUNTITO
    
    
    g.setColor(Color.BLACK);
    g.drawLine(253, 220, 253, 260);
     }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDoraimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDoraimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDoraimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDoraimon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDoraimon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
